Repository area17/twill, pull requests merged in 2022-05, with the labels that each got.

#1617 Make site-link translatable
  lang/en/lang.php
  lang/tr/lang.php
  views/partials/navigation/_global_navigation.blade.php
Labels: type: enhancement

#1618 Fix SQL error on twill:refresh-crops command
  src/Commands/RefreshCrops.php
Labels: type: bug

#1620 Fix locale if intl extension is missing.
  src/Helpers/i18n_helpers.php
Labels: type: bug

#1621 #809: Fix placeholder quotes.
  views/partials/form/_input.blade.php
  views/partials/form/_wysiwyg.blade.php
Labels: type: bug

#1613 Search input length trigger change
  frontend/js/components/Search.vue
Labels: type: enhancement

#1590 deleted items whose parent are not deleted should now be correctly displayed in trash list
  src/Models/Behaviors/HasNesting.php
  src/Models/NestedsetCollection.php
  src/Repositories/Behaviors/HandleNesting.php
Labels: type: enhancement

#1579 [3.x] #375 file delete folder
  src/Repositories/FileRepository.php
  src/Repositories/MediaRepository.php
  src/Repositories/ModuleRepository.php
  tests/integration/Behaviors/CreatesFile.php
  tests/integration/Behaviors/CreatesMedia.php
  tests/integration/FileLibraryTest.php
  tests/integration/Isolation/MediaFileDeleteTest.php
  tests/integration/MediaLibraryTest.php
Labels: Needs a test
